version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  zookeeper-web:
    image: goodguide/zk-web
    container_name: zookeeper-web
    ports:
      - "8080:8080"
    environment:
      - ZKWEB_PORT=8080
      - ZKWEB_CREDENTIALS=admin:hello